### ISSUE TITLE
Access to Tables/Views/Data/Libraries

### ISSUE THREAD

**Issue by engmtcdrm** [sassoftware/vscode-sas-extension#9] opened 2022-06-08 14:32 UTC
It would be awesome if we could get support for accessing libraries and dat in VSC. Only being able to see data via proc print is not viable in a development environment.

**Comment by mail2fei** [comment] 2022-07-20 15:18
This request is already in our feature backlog.

**Comment by scottdover** [comment] 2023-02-16 19:14
This is a duplicate of https://github.com/sassoftware/vscode-sas-extension/issues/129

**Closed by scottdover** 2023-02-16 19:14 UTC
Labels: feature request, UI needed
