### ISSUE TITLE
Specify Autoexec for connection to a local SAS install

### ISSUE THREAD

**Issue by JBDB1** [sassoftware/vscode-sas-extension#930] opened 2024-04-07 21:16 UTC
Without the ability to specify an autoexec, people at our site will not be able to use this extension for SAS for any real work. All setups (librefs, stuff that run on invocation to configure the environment) are managed via autoexec's

The solution I would like:
Ability to specify name of Autoexec file for connection to a local SAS install in the JSON settings. Similar to what is possible for Viya connections

SAS version:
Local install of SAS Foundation 9.4

**Comment by scnwwu** [comment] 2024-04-08 06:41
similar to #656 (which I don't know why it was closed)

**Comment by snlwih** [comment] 2024-04-11 13:47
Duplicate of #656. Close this one and will label it as duplicate.

**Closed by snlwih** 2024-04-11 13:47 UTC
Labels: feature request

**Comment by jzadra** [comment] 2026-04-13 21:55
Still really need this for my work site
