### ISSUE TITLE
SAS Notebook fails to open with error after upgrading to 1.7.0

### ISSUE THREAD

**Issue by smorrisj** [sassoftware/vscode-sas-extension#822] opened 2024-02-12 17:24 UTC
**Describe the bug**
After updating to version 1.7 of the extension, sas notebook files are rendering with an error:
![image](https://github.com/sassoftware/vscode-sas-extension/assets/117842602/e78a6283-a5d3-4529-9afd-c9f3fd9b14da)

**Steps to reproduce**

1. Install v 1.6.0 extension vsix
2. Clone out the examples from [sas access](https://github.com/sassoftware/sas-access-samples)
3. Open up [this](https://github.com/sassoftware/sas-access-samples/blob/master/SAS%20Viya/JDBC/jdbcSmokeTesting_template.sasnb) file
4. Observe that it renders correctly without an error.
5. By default, the marketplace will auto-update the extension. Click extensions and Click Update. Then, click Reload. VSCode will restart.
6. On restart, notice that the .sasnb file is still open, but now there is an error. See error in screenshot above.

**Expected behavior**
SAS Notebook files should continue to open/render after the upgrade.

**Screenshots**
See Above

**Environment (please complete the following information):**
Client OS: Windows
Extension version: v1.6.0 -> v1.7.0
VSCode Version: 1.86.1

**Additional context**

**Comment by scottdover** [comment] 2024-02-15 15:33
Closing as a duplicate of https://github.com/sassoftware/vscode-sas-extension/issues/825

**Closed by scottdover** 2024-02-15 15:33 UTC
Labels: bug
