### ISSUE TITLE
Local/Remote IOM connection - support View Data

### ISSUE THREAD

**Issue by litn2018** [sassoftware/vscode-sas-extension#595] opened 2023-11-02 16:08 UTC
Now local SAS connection did not support to view the content of data sets. Such a function is available in Enterprise Guide. If this function can be implemented, it will make VSCode extension more usable.

thanks

**Comment by nathan-lindstedt** [comment] 2023-11-02 21:11
This feature request was also raised here: https://github.com/sassoftware/vscode-sas-extension/issues/347. Please show your support for this ask there as well.

**Comment by scottdover** [comment] 2024-02-19 19:38
Hey @nathan-lindstedt. At the moment, this is the highest priority. I'm waiting for some resources around documentation, but as soon as those are available this work will begin. This should be released by 2.0, and will ideally be part of the 1.8 release.

**Comment by scottdover** [comment] 2024-04-30 20:11
This is a duplicate of https://github.com/sassoftware/vscode-sas-extension/issues/680

**Closed by scottdover** 2024-04-30 20:11 UTC
Labels: feature request
