### ISSUE TITLE
Library view into SAS 9.4 extension

### ISSUE THREAD

**Issue by i0355695** [sassoftware/vscode-sas-extension#697] opened 2023-12-14 10:25 UTC
Display a panel to view the library allocated through the SAS 9.4 extension, as it is on SAS viya extension. 
Not easy to manipulate the data just created into those librairies.
<img width="1383" alt="Capture d’écran 2023-12-14 à 11 17 52" src="https://github.com/sassoftware/vscode-sas-extension/assets/102238276/f31ad08b-2d6a-4ab1-9383-8fa516d7880b">

**Comment by scottdover** [comment] 2023-12-14 16:21
Hey @i0355695! This appears to be a duplicate of https://github.com/sassoftware/vscode-sas-extension/issues/680. This is the next priority on our roadmap, so there should be updates soon.

**Closed by scottdover** 2023-12-14 16:21 UTC
